server:
  port: 9090

spring:
  application:
    name: Product Microservice for PRODUCTION Environment
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping-prod

product:
  currencies:
    - INR
    - USD
    - EUR

---

server:
  port: 9091

spring:
  application:
    name: Product Microservice Main
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  boot:
    admin:
      client:
        url:
          - http://localhost:8081
  #profiles:
    #active: dev, qa, prod

product:
  currencies:
    - INR
    - USD
    - EUR

logging:
  file:
    name: d:\logs\product.log
  logback:
    rollingpolicy:
      max-file-size: 5KB
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mongo:
      enabled: false              # In case you want to stop showing mongodb in health check, as default its true
info:
  app:
    name: Product Microservice
    version: 1.0
    description: Add and retrieve product information

springdoc:
  api-docs:
    path: /product-docs               # I'm renaming path of openAPI to : http://localhost:9091/product-docs
                                      # To visit productAPI swagger page : http://localhost:9091/swagger-ui.html